Init script appears to be working well

diff --git a/prototype-pidee-service-installer/assets/pidee.init b/prototype-pidee-service-installer/assets/pidee.init
--- a/prototype-pidee-service-installer/assets/pidee.init
+++ b/prototype-pidee-service-installer/assets/pidee.init
@@ -2,34 +2,21 @@
 # ------------------------------------------------------------------------------ 
 # SOME INFOS: fairly standard (debian) init script.
 #             Note that node doesn't create a PID file (hence --make-pidfile) 
-#             has to be run in the background (hence --background)
-#             and NOT as root (hence --chuid)
 #
 # MORE INFOS: INIT SCRIPT       http://www.debian.org/doc/debian-policy/ch-opersys.html#s-sysvinit
 #             INIT-INFO RULES   http://wiki.debian.org/LSBInitScripts
 #             INSTALL/REMOVE    http://www.debian-administration.org/articles/28
 # ------------------------------------------------------------------------------
-#                                                                              #
-#                     BEGIN <MODIFY TO REFLECT YOUR SETTINGS>                  #
 #
-#  1) Don't forget to also modify the COMMENTED fields in the "### BEGIN INIT INFO"
-#     below (don't uncomment them) if you wish to install system-wide with update-rc.d
-#     eg: provides, Short-Description, Description
-#
-#  2) in case you have different node.js servers running, each init.d script should
-#     (obviously) have a UNIQUE BASE name so that PIDS do not conflict
-#     --> name them accordingly
-#     eg: node_static_server, node_express1, node_load_balancer.sh...
-#
-#  3) copy the renamed/modified script(s) to /etc/init.d
+#  1) copy the renamed/modified script(s) to /etc/init.d
 #     chmod 755,
 #
-#  4) if you wish the Daemon to be lauched at boot / stopped at shutdown :
+#  2) if you wish the Daemon to be lauched at boot / stopped at shutdown :
 #     INSTALL : update-rc.d scriptname defaults 
 #     (UNINSTALL : update-rc.d -f  scriptname remove)
 #
-#  5)  based on : Debian /etc/init.d/skeleton
-#      modified by : Peter Host (www.oghme.com)
+#  3)  based on : Debian /etc/init.d/skeleton
+
 
 ### BEGIN INIT INFO
 # Provides:          pidee
@@ -48,54 +35,40 @@ PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin # modify if you need
 
 # path to your node.js server/app
 # NB: don't use ~/ in path
-DAEMON_ARGS="/usr/sbin/pidee-service"
+NODE_SCRIPT="/usr/sbin/pidee-service"
 
-# whatever fancy description you like
-DESC="node.js http server"
+# description
+DESC="Pidee daemon"
 
 # USER who OWNS the daemon process (no matter whoever runs the init script)
 # user:group (if no group is specified, the primary GID for that user is used)
-NODEUSER=pidee:pidee
-
-# in case the init script is run by non-root user, you need to
-# indicate a directory writeable by $NODEUSER to store the PID file
-# NB : 1) /usr/local/var/run does not exist by DEFAULT. Either create it
-#         or choose one of your own liking.
-#      2) node, npm,... are best NOT installed/run as ROOT.
-#         (see here: https://github.com/isaacs/npm/blob/master/README.md)
-# LOCAL_VAR_RUN=/usr/local/var/run
-LOCAL_VAR_RUN=/var/run
+NODE_USER=root
 
 # name of the node.js executable
 NAME=node
 
 # this SHOULD POINT TO where your node executable is
-DAEMON=/usr/lib/pidee/node/bin/$NAME
+NODE_BIN=/usr/lib/pidee/node/bin/$NAME
 
-#                   END </MODIFY TO REFLECT YOUR SETTINGS>                     #
-#                (Nothing else to modify from this point on...)                #
-# ------------------------------------------------------------------------------ 
-
-
-
+## start-stop-daemon exist statuses
+# Exit status:
+#   0 = done
+#   1 = nothing done (=> 0 if --oknodo)
+#   2 = with --retry, processes would not die
+#   3 = trouble
+# Exit status with --status:
+#   0 = program is running
+#   1 = program is not running and the pid file exists
+#   3 = program is not running
+#   4 = unable to determine status
 
 
 # Do NOT "set -e"
 
-# in case this script is run by root, override user setting
-# [ $UID -eq 0 ] && LOCAL_VAR_RUN=/var/run
-THIS_ARG=$0
-INIT_SCRIPT_NAME=`basename $THIS_ARG`
-[ -h $THIS_ARG ] && INIT_SCRIPT_NAME=`basename $(readlink $THIS_ARG)` # in case of symlink
-INIT_SCRIPT_NAME_NOEXT=${INIT_SCRIPT_NAME%.*}                            
-PIDFILE="$LOCAL_VAR_RUN/$INIT_SCRIPT_NAME_NOEXT.pid"
-SCRIPTNAME=/etc/init.d/$INIT_SCRIPT_NAME
+PIDFILE="/var/run/pidee.pid"
 
 # Exit if the package is not installed
-[ -x "$DAEMON" ] ||  { echo "can't find Node.js ($DAEMON)"  >&2; exit 0; }
-
-# Exit if the 'run' folder is not present
-[ -d "$LOCAL_VAR_RUN" ] || { echo "Directory $LOCAL_VAR_RUN does not exist. Modify the '$INIT_SCRIPT_NAME_NOEXT' init.d script ($THIS_ARG) accordingly" >&2; exit 0; }
+[ -x "$NODE_BIN" ] ||  { echo "Can't find Node.js ($NODE_BIN)"  >&2; exit 0; }
 
 # Read configuration variable file if it is present
 [ -r /etc/default/$INIT_SCRIPT_NAME ] && . /etc/default/$INIT_SCRIPT_NAME
@@ -112,57 +85,30 @@ SCRIPTNAME=/etc/init.d/$INIT_SCRIPT_NAME
 
 # Function that starts the daemon/service
 do_start() {
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
 	start-stop-daemon \
 		--start \
 		--quiet \
-		--pidfile $PIDFILE \
-		--chuid $NODEUSER \
-		--background \
-		--exec $DAEMON \
-		--test > /dev/null \
-		|| { [ "$VERBOSE" != no ] && log_daemon_msg  "  --->  Daemon already running $DESC" "$INIT_SCRIPT_NAME_NOEXT"; return 1; }
-
-	start-stop-daemon \
-		--start \
-		--quiet \
-		--chuid $NODEUSER \
 		--make-pidfile \
 		--pidfile $PIDFILE \
+		--name $NAME \
+		--chuid $NODE_USER \
 		--background \
-		--exec $DAEMON -- \
-		$DAEMON_ARGS \
-		|| { [ "$VERBOSE" != no ] && log_daemon_msg  "  --->  could not be start $DESC" "$INIT_SCRIPT_NAME_NOEXT"; return 2; }
+		--startas $NODE_BIN -- $NODE_SCRIPT
+		# || { [ "$VERBOSE" != no ] && log_daemon_msg  "Could not start $DESC" "pidee"; return 2; }
+
+	# Capture start-stop-daemon return code
+	RETVAL="$?"
 
 	# Add code here, if necessary, that waits for the process to be ready
 	# to handle requests from services started subsequently which depend
 	# on this one.  As a last resort, sleep for some time.
-	[ "$VERBOSE" != no ] && log_daemon_msg  "  --->  started $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+	[ "$VERBOSE" != no ] && log_daemon_msg  "started $DESC" "pidee"
+
+	return "$RETVAL"
 }
 
 # Function that stops the daemon/service
 do_stop() {
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon \
-		--stop \
-		--quiet \
-		--retry=TERM/30/KILL/5 \
-		--pidfile $PIDFILE  \
-		--chuid $NODEUSER \
-		--exec $DAEMON
-
-	RETVAL="$?"
-
-	#[ "$VERBOSE" != no ] && [ "$RETVAL" = 1 ] && log_daemon_msg  "  --->  SIGKILL failed => hardkill $DESC" "$INIT_SCRIPT_NAME_NOEXT"
-	[ "$RETVAL" = 2 ] && return 2
-
 	# Wait for children to finish too if this is a daemon that forks
 	# and if the daemon is only ever run from this initscript.
 	# If the above conditions are not satisfied then add some other code
@@ -175,24 +121,24 @@ do_stop() {
 		--quiet \
 		--oknodo \
 		--retry=0/3/KILL/5 \
-		--pidfile $PIDFILE  \
-		--chuid $NODEUSER \
-		--exec $DAEMON -- $DAEMON_ARGS
+		--pidfile $PIDFILE \
+		--name $NAME \
+		--chuid $NODE_USER \
+		--startas $NODE_BIN -- $NODE_SCRIPT
 
-	[ "$?" = 2 ] && return 2
+	# Capture start-stop-daemon return code
+	RETVAL="$?"
 
 	# Many daemons don't delete their pidfiles when they exit.
-	rm -f $PIDFILE
-
-	# Log according to return values of the above
-	[ "$VERBOSE" != no ] && [ "$RETVAL" = 1 ] && log_daemon_msg "  --->  $DESC not running" "$INIT_SCRIPT_NAME_NOEXT"
-	[ "$VERBOSE" != no -a "$RETVAL" = 0 ] && log_daemon_msg "  --->  $DESC stopped" "$INIT_SCRIPT_NAME_NOEXT"
+	[ "$RETVAL" = 0 ] && rm -f $PIDFILE
+	[ "$RETVAL" = 0 ] && [ "$VERBOSE" != no ] && log_daemon_msg  "Stopped $DESC" "pidee"
 
 	return "$RETVAL"
 }
 
 # Function that sends a SIGHUP to the daemon/service
 do_reload() {
+	# not in use
 	# If the daemon can reload its configuration without
 	# restarting (for example, when it is sent a SIGHUP),
 	# then implement that here.
@@ -202,7 +148,7 @@ do_reload() {
 		--quiet \
 		--signal 1 \
 		--pidfile $PIDFILE  \
-		--chuid $NODEUSER \
+		--chuid $NODE_USER \
 		--name $NAME
 
 	return 0
@@ -225,22 +171,23 @@ do_status() {
 
 	if [ -n "$RUNNING" ]; then
 		if [ $ISPIDACTIVE ]; then 
-			log_success_msg "$INIT_SCRIPT_NAME_NOEXT (launched by $USER) (--chuid $NODEUSER) is running"
+			log_success_msg "Pidee (launched by `id -un`) (--chuid $NODE_USER) is running"
 			exit 0      
 		fi
 	else
 		if [ -f $PIDFILE ]; then
-			log_success_msg "$INIT_SCRIPT_NAME_NOEXT (launched by $USER) (--chuid $NODEUSER) is not running, phantom pidfile $PIDFILE"
+			log_success_msg "Pidee (launched by `id -un`) (--chuid $NODE_USER) is not running, phantom pidfile $PIDFILE"
 			exit 1
 		else
-			log_success_msg "no instance launched by $USER, of $INIT_SCRIPT_NAME_NOEXT (--chuid $NODEUSER) found"
+			log_success_msg "No instance launched by `id -un`, of pidee (--chuid $NODE_USER) found"
 			exit 3
 		fi
 	fi
 }
 
+## TODO: change this to use start-stop-daemon --status
 running() {
-	RUNSTAT=$(start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $NODEUSER --background --exec $DAEMON --test > /dev/null)
+	RUNSTAT=$(start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $NODE_USER --background --startas $NODE_BIN --test > /dev/null)
 	if [ "$?" = 1 ]; then
 		echo y
 	fi
@@ -249,15 +196,15 @@ running() {
 
 case "$1" in
 	start)
-		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "pidee"
 		do_start
 		case "$?" in
 			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+			2|3) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
 		esac
 	;;
 	stop)
-		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "pidee"
 		do_stop
 		case "$?" in
 			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
@@ -274,7 +221,7 @@ case "$1" in
 	restart|force-reload)
 		# If the "reload" option is implemented then remove the
 		# 'force-reload' alias
-		log_daemon_msg "Restarting $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+		log_daemon_msg "Restarting $DESC" "pidee"
 		do_stop
 		case "$?" in
 			0|1)
@@ -295,8 +242,8 @@ case "$1" in
 		do_status
 	;;
 	*)
-		#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-		echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
+		#echo "Usage: /etc/init.d/pidee {start|stop|restart|reload|force-reload}" >&2
+		echo "Usage: /etc/init.d/pidee {start|stop|restart|force-reload}" >&2
 		exit 3
 	;;
 esac
