massive init and maintainer scripts update

diff --git a/prototype-pidee-service-installer/assets/pidee.init b/prototype-pidee-service-installer/assets/pidee.init
--- a/prototype-pidee-service-installer/assets/pidee.init
+++ b/prototype-pidee-service-installer/assets/pidee.init
@@ -1,223 +1,304 @@
 #!/bin/sh
+# ------------------------------------------------------------------------------ 
+# SOME INFOS: fairly standard (debian) init script.
+#             Note that node doesn't create a PID file (hence --make-pidfile) 
+#             has to be run in the background (hence --background)
+#             and NOT as root (hence --chuid)
+#
+# MORE INFOS: INIT SCRIPT       http://www.debian.org/doc/debian-policy/ch-opersys.html#s-sysvinit
+#             INIT-INFO RULES   http://wiki.debian.org/LSBInitScripts
+#             INSTALL/REMOVE    http://www.debian-administration.org/articles/28
+# ------------------------------------------------------------------------------
+#                                                                              #
+#                     BEGIN <MODIFY TO REFLECT YOUR SETTINGS>                  #
+#
+#  1) Don't forget to also modify the COMMENTED fields in the "### BEGIN INIT INFO"
+#     below (don't uncomment them) if you wish to install system-wide with update-rc.d
+#     eg: provides, Short-Description, Description
+#
+#  2) in case you have different node.js servers running, each init.d script should
+#     (obviously) have a UNIQUE BASE name so that PIDS do not conflict
+#     --> name them accordingly
+#     eg: node_static_server, node_express1, node_load_balancer.sh...
+#
+#  3) copy the renamed/modified script(s) to /etc/init.d
+#     chmod 755,
+#
+#  4) if you wish the Daemon to be lauched at boot / stopped at shutdown :
+#     INSTALL : update-rc.d scriptname defaults 
+#     (UNINSTALL : update-rc.d -f  scriptname remove)
+#
+#  5)  based on : Debian /etc/init.d/skeleton
+#      modified by : Peter Host (www.oghme.com)
+
 ### BEGIN INIT INFO
 # Provides:          pidee
-# Required-Start:    $local_fs $remote_fs $syslog
-# Required-Stop:     $local_fs $remote_fs $syslog
+# Required-Start:    $local_fs $remote_fs $named $syslog
+# Required-Stop:     $local_fs $remote_fs $named $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: GPIO service for the Pidee Raspberry Pi board add-on
-# Description:       This file should be used to start and stop pidee.
+# Short-Description: DEBIAN initscript for node.js servers/apps
+# Description:       Pidee GPIO server
 ### END INIT INFO
 
 # Author: Tommaso Lanza <pidee@theworkers.net>
 
-PATH=/sbin:/usr/sbin:/bin:/usr/bin
-PIDFILE=/var/run/pidee.pid
-CONFIG=/etc/pidee/index.js
-NODE=/usr/lib/pidee/node/bin/node
-PIDEE=/usr/sbin/pidee-service
-RUNDIR=/run/pidee
-EXTRAOPTS=
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
+PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin # modify if you need
 
-## These lines can be useful when wishing to expose require() paths
-## which would otherwise be unreachable to relocated node scripts
-# export NODE_PATH="/usr/lib/pidee/pidee/node_modules:$NODE_PATH"
-# export NODE_PATH="/usr/lib/pidee/pidee/libs:$NODE_PATH"
+# path to your node.js server/app
+# NB: don't use ~/ in path
+DAEMON_ARGS="/usr/sbin/pidee-service"
 
-# Check if pidee is where it's supposed to be. Bail out if not.
-test -x $PIDEE || exit 0
+# whatever fancy description you like
+DESC="node.js http server"
 
-# Check if node is where it's supposed to be. Bail out if not.
-test -x $NODE || exit 0
+# USER who OWNS the daemon process (no matter whoever runs the init script)
+# user:group (if no group is specified, the primary GID for that user is used)
+NODEUSER=pidee:pidee
 
-# Suck up the default conf.
-# TODO: make this node-interpreted?
-if [ -e /etc/default/pidee ]; then
-	. /etc/default/pidee
-fi
+# in case the init script is run by non-root user, you need to
+# indicate a directory writeable by $NODEUSER to store the PID file
+# NB : 1) /usr/local/var/run does not exist by DEFAULT. Either create it
+#         or choose one of your own liking.
+#      2) node, npm,... are best NOT installed/run as ROOT.
+#         (see here: https://github.com/isaacs/npm/blob/master/README.md)
+# LOCAL_VAR_RUN=/usr/local/var/run
+LOCAL_VAR_RUN=/var/run
 
-# Ensure we have a config file in /etc
-test -f "$CONFIG" || exit 0
+# name of the node.js executable
+NAME=node
 
-# Variables that affect the behavior of boot scripts
-# http://manpages.ubuntu.com/manpages/precise/man5/rcS.5.html
-[ -f /etc/default/rcS ] && . /etc/default/rcS
+# this SHOULD POINT TO where your node executable is
+DAEMON=/usr/lib/pidee/node/bin/$NAME
+
+#                   END </MODIFY TO REFLECT YOUR SETTINGS>                     #
+#                (Nothing else to modify from this point on...)                #
+# ------------------------------------------------------------------------------ 
+
+
+
+
+
+# Do NOT "set -e"
+
+# in case this script is run by root, override user setting
+# [ $UID -eq 0 ] && LOCAL_VAR_RUN=/var/run
+THIS_ARG=$0
+INIT_SCRIPT_NAME=`basename $THIS_ARG`
+[ -h $THIS_ARG ] && INIT_SCRIPT_NAME=`basename $(readlink $THIS_ARG)` # in case of symlink
+INIT_SCRIPT_NAME_NOEXT=${INIT_SCRIPT_NAME%.*}                            
+PIDFILE="$LOCAL_VAR_RUN/$INIT_SCRIPT_NAME_NOEXT.pid"
+SCRIPTNAME=/etc/init.d/$INIT_SCRIPT_NAME
+
+# Exit if the package is not installed
+[ -x "$DAEMON" ] ||  { echo "can't find Node.js ($DAEMON)"  >&2; exit 0; }
+
+# Exit if the 'run' folder is not present
+[ -d "$LOCAL_VAR_RUN" ] || { echo "Directory $LOCAL_VAR_RUN does not exist. Modify the '$INIT_SCRIPT_NAME_NOEXT' init.d script ($THIS_ARG) accordingly" >&2; exit 0; }
+
+# Read configuration variable file if it is present
+[ -r /etc/default/$INIT_SCRIPT_NAME ] && . /etc/default/$INIT_SCRIPT_NAME
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
 
+# uncomment to override system setting
+# VERBOSE=yes
 
-check_pidee_config()
-{
-	# Exit if config check fails
-	# TODO: check all configs.js provide a function that returns an object
-	$PIDEE -c -f "$CONFIG" >/dev/null
-	if [ $? -eq 1 ]; then
-		log_end_msg 1
-		exit 1
-	fi
+# Function that starts the daemon/service
+do_start() {
+	# Return
+	#   0 if daemon has been started
+	#   1 if daemon was already running
+	#   2 if daemon could not be started
+	start-stop-daemon \
+		--start \
+		--quiet \
+		--pidfile $PIDFILE \
+		--chuid $NODEUSER \
+		--background \
+		--exec $DAEMON \
+		--test > /dev/null \
+		|| { [ "$VERBOSE" != no ] && log_daemon_msg  "  --->  Daemon already running $DESC" "$INIT_SCRIPT_NAME_NOEXT"; return 1; }
+
+	start-stop-daemon \
+		--start \
+		--quiet \
+		--chuid $NODEUSER \
+		--make-pidfile \
+		--pidfile $PIDFILE \
+		--background \
+		--exec $DAEMON -- \
+		$DAEMON_ARGS \
+		|| { [ "$VERBOSE" != no ] && log_daemon_msg  "  --->  could not be start $DESC" "$INIT_SCRIPT_NAME_NOEXT"; return 2; }
+
+	# Add code here, if necessary, that waits for the process to be ready
+	# to handle requests from services started subsequently which depend
+	# on this one.  As a last resort, sleep for some time.
+	[ "$VERBOSE" != no ] && log_daemon_msg  "  --->  started $DESC" "$INIT_SCRIPT_NAME_NOEXT"
 }
 
-pidee_start()
-{
-	# Create /run/pidee directory, take ownership, chmod it.
-	[ -d "$RUNDIR" ] || mkdir "$RUNDIR"
-	chown pidee:pidee "$RUNDIR"
-	chmod 2775 "$RUNDIR"
-
-	# check_pidee_config
-
-	# User start-stop-daemon to start the pidee-service as a deamon
+# Function that stops the daemon/service
+do_stop() {
+	# Return
+	#   0 if daemon has been stopped
+	#   1 if daemon was already stopped
+	#   2 if daemon could not be stopped
+	#   other if a failure occurred
 	start-stop-daemon \
+		--stop \
+		--quiet \
+		--retry=TERM/30/KILL/5 \
+		--pidfile $PIDFILE  \
+		--chuid $NODEUSER \
+		--exec $DAEMON
+
+	RETVAL="$?"
+
+	#[ "$VERBOSE" != no ] && [ "$RETVAL" = 1 ] && log_daemon_msg  "  --->  SIGKILL failed => hardkill $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+	[ "$RETVAL" = 2 ] && return 2
+
+	# Wait for children to finish too if this is a daemon that forks
+	# and if the daemon is only ever run from this initscript.
+	# If the above conditions are not satisfied then add some other code
+	# that waits for the process to drop all resources that could be
+	# needed by services started subsequently.  A last resort is to
+	# sleep for some time.
+
+	start-stop-daemon \
+		--stop \
 		--quiet \
 		--oknodo \
-		--start \
-		--background \
-		--pidfile "$PIDFILE" \
-		--exec $PIDEE -- -f "$CONFIG" -D -p "$PIDFILE" \
-		$EXTRAOPTS || return 2
+		--retry=0/3/KILL/5 \
+		--pidfile $PIDFILE  \
+		--chuid $NODEUSER \
+		--exec $DAEMON -- $DAEMON_ARGS
+
+	[ "$?" = 2 ] && return 2
+
+	# Many daemons don't delete their pidfiles when they exit.
+	rm -f $PIDFILE
+
+	# Log according to return values of the above
+	[ "$VERBOSE" != no ] && [ "$RETVAL" = 1 ] && log_daemon_msg "  --->  $DESC not running" "$INIT_SCRIPT_NAME_NOEXT"
+	[ "$VERBOSE" != no -a "$RETVAL" = 0 ] && log_daemon_msg "  --->  $DESC stopped" "$INIT_SCRIPT_NAME_NOEXT"
+
+	return "$RETVAL"
+}
+
+# Function that sends a SIGHUP to the daemon/service
+do_reload() {
+	# If the daemon can reload its configuration without
+	# restarting (for example, when it is sent a SIGHUP),
+	# then implement that here.
+
+	start-stop-daemon \
+		--stop \
+		--quiet \
+		--signal 1 \
+		--pidfile $PIDFILE  \
+		--chuid $NODEUSER \
+		--name $NAME
+
 	return 0
 }
 
-pidee_stop()
-{
-	# If there's no pid file, exit already
-	if [ ! -f $PIDFILE ] ; then
-		# This is a success according to LSB
-		return 0
-	fi
+# Function that returns the daemon 
+do_status() {
+	# http://refspecs.freestandards.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
+	# 0 program is running or service is OK
+	# 1 program is dead and /var/run pid file exists
+	# (2 program is dead and /var/lock lock file exists) (not used here)
+	# 3 program is not running
+	# 4 program or service status is unknown
 
-	# Try to stop the daemon with --stop
-	ret=0
-	for pid in $(cat $PIDFILE); do
-		start-stop-daemon \
-			--quiet \
-			--oknodo \
-			--stop \
-			--retry 5 \
-			--pid $pid \
-			--exec $PIDEE || ret=$?
-	done
+	RUNNING=$(running)
 
-	# If start-stop-daemon exits 0, delete the pidfile
-	[ $ret -eq 0 ] && rm -f $PIDFILE
+	# $PIDFILE corresponds to a live $NAME process
+	ispidactive=$(pidof $NAME | grep `cat $PIDFILE 2>&1` >/dev/null 2>&1)
+	ISPIDACTIVE=$?
 
-	return $ret
-}
-
-pidee_reload()
-{
-	# This is mostly a stub
-
-	# check_pidee_config
-
-	$PIDEE -f "$CONFIG" -p $PIDFILE -D $EXTRAOPTS -sf $(cat $PIDFILE) \
-		|| return 2
-	return 0
-}
-
-pidee_status()
-{
-	if [ ! -f $PIDFILE ] ; then
-		# program not running
-		return 3
-	fi
-
-	# Check for a leftover pidfile
-	for pid in $(cat $PIDFILE) ; do
-		if ! ps --no-headers p "$pid" | grep pidee > /dev/null ; then
-			# program running, bogus pidfile
-			return 1
+	if [ -n "$RUNNING" ]; then
+		if [ $ISPIDACTIVE ]; then 
+			log_success_msg "$INIT_SCRIPT_NAME_NOEXT (launched by $USER) (--chuid $NODEUSER) is running"
+			exit 0      
 		fi
-	done
+	else
+		if [ -f $PIDFILE ]; then
+			log_success_msg "$INIT_SCRIPT_NAME_NOEXT (launched by $USER) (--chuid $NODEUSER) is not running, phantom pidfile $PIDFILE"
+			exit 1
+		else
+			log_success_msg "no instance launched by $USER, of $INIT_SCRIPT_NAME_NOEXT (--chuid $NODEUSER) found"
+			exit 3
+		fi
+	fi
+}
 
-	return 0
+running() {
+	RUNSTAT=$(start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $NODEUSER --background --exec $DAEMON --test > /dev/null)
+	if [ "$?" = 1 ]; then
+		echo y
+	fi
 }
 
 
 case "$1" in
-start)
-	log_daemon_msg "Starting pidee-service" "pidee-service"
-	pidee_start
-	ret=$?
-	case "$ret" in
-	0)
-		log_end_msg 0
-		;;
-	1)
-		log_end_msg 1
-		echo "pid file '$PIDFILE' found, pidee-service not started."
-		;;
-	2)
-		log_end_msg 1
-		;;
-	esac
-	exit $ret
+	start)
+		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+		do_start
+		case "$?" in
+			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		esac
 	;;
-stop)
-	log_daemon_msg "Stopping pidee-service" "pidee-service"
-	pidee_stop
-	ret=$?
-	case "$ret" in
-	0|1)
-		log_end_msg 0
-		;;
-	2)
-		log_end_msg 1
-		;;
-	esac
-	exit $ret
+	stop)
+		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+		do_stop
+		case "$?" in
+			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+		esac
 	;;
-reload|force-reload)
-	log_daemon_msg "Reloading pidee-service" "pidee-service"
-	pidee_reload
-	ret=$?
-	case "$ret" in
-	0|1)
-		log_end_msg 0
-		;;
-	2)
-		log_end_msg 1
-		;;
-	esac
-	exit $ret
+	# reload|force-reload)
+	# 	# If do_reload() is not implemented then leave this commented out
+	# 	# and leave 'force-reload' as an alias for 'restart'.
+	# 	log_daemon_msg "Reloading $DESC" "$NAME"
+	# 	do_reload
+	# 	log_end_msg $?
+	# ;;
+	restart|force-reload)
+		# If the "reload" option is implemented then remove the
+		# 'force-reload' alias
+		log_daemon_msg "Restarting $DESC" "$INIT_SCRIPT_NAME_NOEXT"
+		do_stop
+		case "$?" in
+			0|1)
+				do_start
+				case "$?" in
+					0) log_end_msg 0 ;;
+					1) log_end_msg 1 ;; # Old process is still running
+					*) log_end_msg 1 ;; # Failed to start
+				esac
+			;;
+			*)
+				# Failed to stop
+				log_end_msg 1
+			;;
+		esac
 	;;
-restart)
-	log_daemon_msg "Restarting pidee-service" "pidee-service"
-	pidee_stop
-	pidee_start
-	ret=$?
-	case "$ret" in
-	0)
-		log_end_msg 0
-		;;
-	1)
-		log_end_msg 1
-		;;
-	2)
-		log_end_msg 1
-		;;
-	esac
-	exit $ret
+	status)
+		do_status
 	;;
-status)
-	pidee_status
-	ret=$?
-	case "$ret" in
-	0)
-		echo "pidee-service is running."
-		;;
-	1)
-		echo "pidee-service dead, but $PIDFILE exists."
-		;;
 	*)
-		echo "pidee-service not running."
-		;;
-	esac
-	exit $ret
-	;;
-*)
-	echo "Usage: /etc/init.d/pidee {start|stop|reload|restart|status}"
-	exit 2
+		#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+		echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
+		exit 3
 	;;
 esac
 
-:
+exit 0
diff --git a/prototype-pidee-service-installer/assets/postinst b/prototype-pidee-service-installer/assets/postinst
--- a/prototype-pidee-service-installer/assets/postinst
+++ b/prototype-pidee-service-installer/assets/postinst
@@ -1,10 +1,52 @@
 #!/bin/sh
 
-{
-	# Add a pidee system user
-	# http://unix.stackexchange.com/questions/47880/how-debian-package-should-create-user-accounts
-	adduser --system --no-create-home --quiet pidee
-} &> /dev/null
+# This script typically completes any required configuration of the package foo 
+# once foo has been unpacked from its Debian archive (".deb") file. 
+#
+# Often, 'postinst' scripts ask the user for input, and/or warn the user 
+# that if he accepts default values, he should remember to go back and 
+# re-configure that package as the situation warrants.
+#
+# Many 'postinst' scripts then execute any commands necessary to start or
+# restart a service once a new package has been installed or upgraded.
 
-# Start service
-service pidee start &> /dev/null
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+# https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html#s6.1
+
+set -e
+
+case "$1" in
+    configure)
+        
+        # Add pidee user and group
+        adduser --system --group --no-create-home --quiet pidee
+
+        # Start service
+        if [ -f /etc/init.d/pidee ];
+        then
+            service pidee start
+        fi
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+#DEBHELPER#
+
+exit 0
diff --git a/prototype-pidee-service-installer/assets/prerm b/prototype-pidee-service-installer/assets/prerm
--- a/prototype-pidee-service-installer/assets/prerm
+++ b/prototype-pidee-service-installer/assets/prerm
@@ -1,5 +1,42 @@
 #!/bin/sh
 
-{
-	service pidee stop
-} &> /dev/null
+# This script typically stops any daemons which are associated with a package.
+# It is executed before the removal of files associated with the package.
+
+# summary of how this script can be called:
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+set -e
+
+case "$1" in
+    remove|upgrade|deconfigure)
+        # Stop pidee service
+        if [ -f /etc/init.d/pidee ];
+        then
+            service pidee stop
+        fi
+    ;;
+
+    failed-upgrade)
+    ;;
+
+    *)
+        echo "prerm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
