Change equality comparison and null errors

diff --git a/prototype-pidee-service-installer/assets/postrm b/prototype-pidee-service-installer/assets/postrm
--- a/prototype-pidee-service-installer/assets/postrm
+++ b/prototype-pidee-service-installer/assets/postrm
@@ -25,11 +25,12 @@ case "$1" in
         ## Below two methods to sniff for systemd being in use
         ## 1 = good
         ## 0 = bad
-        grep_systemd=$(sudo stat /proc/1/exe | grep -cim1 systemd)
-        pidof_systemd=$(pidof systemd && echo 1 || echo 0)
+        ## these are /dev/null'd because if nothing matches then we have a bad return code and the install fails
+        grep_systemd=$(sudo stat /proc/1/exe | grep -cim1 systemd) &> /dev/null
+        pidof_systemd=$(pidof systemd && echo 1 || echo 0) &> /dev/null
 
         # Check if we have systemd
-        if [ $grep_systemd = 1 ] || [ $pidof_systemd = 1 ]; then
+        if [ $grep_systemd -eq 1 ] || [ $pidof_systemd -eq 1 ]; then
             # TODO: should we check for [ hash systemctl 2> /dev/null ] first?
 
             # Check if we are actually uninstalling or just upgrading
@@ -47,6 +48,7 @@ case "$1" in
         else
             # Check if we are actually uninstalling or just upgrading
             if [ $1 != upgrade ]; then
+
                 # Remove from boot rc.d and silence errors (and stdout) if already installed
                 update-rc.d -f pidee remove 2> /dev/null
 
diff --git a/prototype-pidee-service-installer/assets/prerm b/prototype-pidee-service-installer/assets/prerm
--- a/prototype-pidee-service-installer/assets/prerm
+++ b/prototype-pidee-service-installer/assets/prerm
@@ -19,14 +19,21 @@ set -e
 case "$1" in
     remove|upgrade|deconfigure)
 
+        ## Below two methods to sniff for systemd being in use
+        ## 1 = good
+        ## 0 = bad
+        ## these are /dev/null'd because if nothing matches then we have a bad return code and the install fails
+        grep_systemd=$(sudo stat /proc/1/exe | grep -cim1 systemd) &> /dev/null
+        pidof_systemd=$(pidof systemd && echo 1 || echo 0) &> /dev/null
+
         ## Check if we are using systemd
-        if [ $grep_systemd = 1 ] || [ $pidof_systemd = 1 ]; then
+        if [ $grep_systemd -eq 1 ] || [ $pidof_systemd -eq 1 ]; then
             ## TODO: should we check for [ hash systemctl 2> /dev/null ] first?
 
             ## Grep list of available .service(s)
-            pidee_was_here=$(systemctl list-units | grep -cim1 pidee)
+            pidee_was_here=$(systemctl list-units | grep -cim1 pidee) &> /dev/null
 
-            if [ $pidee_was_here = 1 ]; then
+            if [ $pidee_was_here -eq 1 ]; then
                 ## Stop the service
                 systemctl stop pidee 2> /dev/null
             fi
